config/routes.rb
Rails.application.routes.draw do
  
  root 'products#index'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get 'sessions/new'

  get 'signup'  => 'users#new'

  resources :products

  resources :users

end

app/models/product.rb
class Product < ActiveRecord::Base

  validates :nombre, length: { maximum: 20 }, :presence => { message: "No puede dejarse vacío" }
  validates :categoria, length: { maximum: 20 }, :presence => { message: "No puede dejarse vacío" }
  validates :marca, length: { maximum: 20 }, :presence => { message: "No puede dejarse vacío" }
  validates :modelo, length: { maximum: 20 }, :presence => { message: "No puede dejarse vacío" }
  validates :cantidad, length: { maximum: 20 }, :presence => { message: "No puede dejarse vacío" }
  validates :ubicacion, length: { maximum: 20 }, :presence => { message: "No puede dejarse vacío" }

  before_save :set_bar_code

  private

  def set_bar_code
    if self.cod_barra.blank?
      self.cod_barra = self.id.to_s + '0' * 3 + Time.now.to_i.to_s
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  attr_accessor :remember_token

  before_save { email.downcase! }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  private

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :find_product, only: [:show, :edit, :update, :destroy]

  def show
    @product = Product.find(params[:id])
  end

  def index
    @q = Product.ransack(params[:q])
    @products = @q.result(distinct: true).paginate(page: params[:page])
    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.create(product_params)
    respond_to do |format|
      if @product.save
        format.js
      else
        format.json { render json: @product.errors, status: :unprocessable_entity }
        format.html { render action: "create" }
        format.js
      end
    end
  end

  def edit
  end

  def update
    if @product.update(product_params)
			redirect_to product_path
		else
      render 'edit'
		end
  end

  def destroy
    @product.destroy
    redirect_to :back
  end

  private

  def product_params
    params.require(:product).permit(:nombre,
                                    :categoria,
                                    :marca,
                                    :modelo,
                                    :observacion,
                                    :p_compra,
                                    :p_venta,
                                    :cantidad,
                                    :cod_barra,
                                    :cod_qr,
                                    :ubicacion)
  end

  def find_product
			@product = Product.find_by(id: params[:id])

		if !@product
			redirect_to root_path
			flash[:notice] =  "Lo sentimos. No se pudo procesar su solicitud."
		end
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_back_or user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end


  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  # Confirms the correct user.
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def is_admin?
    current_user.admin
  end

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # Returns the user corresponding to the remember token cookie.
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  # Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # Logs out the current user.
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  # Returns true if the given user is the current user.
  def current_user?(user)
    user == current_user
  end

  # Redirects to stored location (or to the default).
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.url if request.get?
  end

end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="#">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container cabecera">
    <div class="navbar-brand">
      <!-- <%= link_to(image_tag("icono.jpg"), root_path, id: "logo" ) %> -->
      <%= link_to "El CELU / v0.75 beta", root_path %>
    </div>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? and  %>
          <li><%= link_to "Productos", products_path %></li>

          <% if is_admin? %>
            <li><%= link_to "Usuarios", users_path %></li>
          <% end %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Cuenta <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Perfil", current_user %></li>
              <li><%= link_to "Configuracion", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Cerrar Sesion", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Iniciar Sesion", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>El Celu</title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/products/_new.html.erb
<section class="product_form">
  <%= form_for Product.new, remote: true, html: { id: 'product-form' } do |f| %>
    <div class="row form_new">
      <div class="col-md-1"></div>
      <div class="form-group">
        <div class="col-md-5">
          <%= f.text_field :nombre, placeholder: "Nombre:", require: true, autofocus: true, class: "form-control" %>
          <%= f.text_field :categoria, placeholder: "Categoria:", require: true, class: "form-control" %>
          <%= f.text_field :marca, placeholder: "Marca:",require: true,  class: "form-control" %>
          <%= f.text_field :modelo, placeholder: "Modelo:",require: true,  class: "form-control" %>
          <%= f.text_field :cantidad, placeholder: "Cantidad:",require: true,  class: "form-control" %>
        </div>
        <div class="col-md-5">
            <%= f.select(:ubicacion, options_for_select([['Depósito', 'Deposito'], ['Local', 'Local']]), {}, {class: "form-control selectpicker"}) %>
          <%= f.text_field :p_compra, placeholder: "Precio de compra: $", class: "form-control" %>
          <%= f.text_field :p_venta, placeholder: "Precio de venta: $", class: "form-control" %>
          <%= f.text_area :observacion, placeholder: "Observacion:", class: "form-control" %>
          <%= f.text_field :cod_barra, placeholder: "Codigo de barra:", class: "form-control" %>
        </div>
      </div>
      <div class="col-md-1"></div>
    </div>
    <div class="modal-footer">
      <div class="col-md-4"></div>
      <div class="col-md-4">
        <%= f.submit "Crear Producto", class: "btn btn-primary" %>
      </div>
      <div class="col-md-4"></div>
    </div>
  <% end %>
</section>

app/views/products/_product.html.erb
<tr id='product-<%= product.id %>'>
  <td class='nombre'><%= product.nombre %></td>
  <td class='modelo'><%= product.modelo %></td>
  <td class='marca'><%= product.marca %></td>
  <td class='categoria'><%= product.categoria %></td>
  <td class='cantidad'><%= product.cantidad %></td>
  <td class='ubicacion'><%= product.ubicacion %></td>
  <% if logged_in? %>
    <td class='p_compra'>$<%= product.p_compra %></td>
  <% end %>
  <td class='p_venta'>$<%= product.p_venta %></td>
  <td class='cod_barra'><%= product.cod_barra %></td>
  <% if product.observacion.blank? %>
    <td class='hay_obs'> No </td>
  <% else %>
    <td class='hay_obs'> Si </td>
  <% end %>

  <td class='acciones'>
    <%= link_to product, { class: "btn btn-sm btn-success" } do %>
      <span class="glyphicon glyphicon-search "></span>
    <% end %>
    <% if logged_in? %>
      <%= link_to edit_product_path(product), { class: "btn btn-sm btn-warning" } do %>
        <span class="glyphicon glyphicon-pencil"></span>
      <% end %>
      <%= link_to product, method: :delete, data: { confirm: "¿Estas seguro?" }, class: "btn btn-sm btn-danger"  do %>
        <span class="glyphicon glyphicon-trash"></span>
      <% end %>
    <% end %>
  </td>
</tr>

app/views/products/edit.html.erb
<br>
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="panel panel-default">
        <div clasS="panel-heading">
          <div class="container">
            <h2>Modificar producto</h2>
          </div>
        </div>
        <div class="panel-body">
          <%= form_for @product do |f| %>
              <div class="form form_edit">
                <div class="row">
                  <div class="col-md-6">

                    <div class="form-group row">
                      <label for="nombre" class="col-md-3 form-control-label">Nombre:</label>
                      <div class="col-md-9">
                        <%= f.text_field :nombre, require: 'true', class: "form-control" %>
                      </div>
                    </div>

                    <div class="form-group row">
                      <label for="modelo" class="col-sm-3 form-control-label">Modelo:</label>
                      <div class="col-sm-9">
                        <%= f.text_field :modelo, require: 'true',  class: "form-control" %>
                      </div>
                    </div>

                    <div class="form-group row">
                      <label for="marca" class="col-sm-3 form-control-label">Marca:</label>
                      <div class="col-sm-9">
                        <%= f.text_field :marca, require: 'true',  class: "form-control" %>
                      </div>
                    </div>

                    <div class="form-group row">
                      <label for="Categoria" class="col-sm-3 form-control-label">Categoria:</label>
                      <div class="col-sm-9">
                        <%= f.text_field :categoria, require: 'true', class: "form-control" %>
                      </div>
                    </div>

                    <div class="form-group row">
                      <label for="Cantidad" class="col-sm-3 form-control-label">Cantidad:</label>
                      <div class="col-sm-9">
                        <%= f.text_field :cantidad, require: 'true',  class: "form-control" %>
                      </div>
                    </div>

                  </div>
                  <div class="col-md-6">

                    <div class="form-group row">
                      <label for="Ubicacion" class="col-sm-3 form-grou-label">Ubicación:</label>
                      <div class="col-sm-9">
                        <%= f.text_field :ubicacion, require: 'true',  class: "form-control" %>
                      </div>
                    </div>

                    <div class="form-group row">
                      <label for="p_compra" class="col-sm-3 form-group-label">Precio de compra:</label>
                      <div class="col-sm-9">
                        <%= f.text_field :p_compra, class: "form-control" %>
                      </div>
                    </div>


                    <div class="form-group row">
                      <label for="p_venta" class="col-sm-3 form-group-label">Precio de venta:</label>
                      <div class="col-sm-9">
                        <%= f.text_field :p_venta, class: "form-control" %>
                      </div>
                    </div>

                    <div class="form-group row">
                      <label for="observacion" class="col-sm-3 form-group-label">Observación:</label>
                      <div class="col-sm-9">
                        <%= f.text_area :observacion, class: "form-control" %>
                      </div>
                    </div>

                    <div class="form-group row">
                      <label for="cod_barra" class="col-sm-3 form-group-label">Codigo de barra:</label>
                      <div class="col-sm-9">
                        <%= f.text_field :cod_barra, class: "form-control" %>
                      </div>
                    </div>

                  </div>
              </div>
              <div class="row">
                <div class="col-md-4 col-offset-1">
                  <%= link_to 'Cancelar', products_path, { class: "btn btn-md btn-info" } %>
                </div>
                <div class="col-md-4 col-offset-4">
                  <%= f.submit "Guardar cambios", class: "btn btn-md btn-success" %>
                </div>
              </div>

            </div>
        </div>
        <% end %>
        <div class="panel-footer data-no-turbolink">
          <br>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-md" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title" id="myModalLabel">Crear nuevo producto</h3>
      </div>
      <div class="modal-body">
          <%= render 'new' %>
      </div>
    </div>
  </div>
</div>

<!-- Contenido Vista -->
<br>

    <!-- Panel -->
    <div class="panel panel-default">

      <header class="panel-heading">
        <div class="row">
          <div class="col-sm-4">
            <!-- <h3 class="cant_prod">Productos (<%= @products.count %>)</h3> -->
            <!-- Barra de busqueda -->
            <div class="imput-group">
              <%= search_form_for @q, remote: true do |f| %>
                <%= f.search_field :nombre_or_modelo_or_marca_or_cod_barra_or_categoria_cont, placeholder: "Ingrese busqueda", class: "form-control" %>
                <span class="input-group-btn">
                  <%= f.submit "Buscar", class: "btn" %>
                </span>
              <% end %>
            </div>

          </div>
          <div class="col-sm-4 paginate-1">
            <%= will_paginate @products %>
          </div>
          <div class="col-sm-4 boton-new">
            <!-- Button trigger modal -->
            <button type="button" class="btn btn-primary btn-md pull-right" data-toggle="modal" data-target="#myModal">
              <span>Crear nuevo producto</span>
            </button>
          </div>
        </div>
      </header>
      <div class="panel-body">
        <table class="table" id="products">
        <tr>
          <th>Nombre</th>
          <th>Marca</th>
          <th>Modelo</th>
          <th>Categoria</th>
          <th>Cantidad</th>
          <th>Ubicacion</th>
          <% if logged_in? %>
            <th>P. Compra</th>
          <% end %>
          <th>P. Venta</th>
          <th>C. Barra</th>
          <th>Observacion</th>
          <th>Acciones</th>
        </tr>
        <% if @products.any? %>
          <% @products.each do |product| %>
            <%= render "product", :product => product %>
          <% end %>
        <% else %>
          <h1>No hay productos cargados</h1>
        <% end %>
        </table>
      </div>
      <div class="panel-footer">
        <div class="row">
          <div class="col-sm-4"></div>
          <div class="col-sm-4">
            <%= will_paginate @products %>
          </div>
          <div class="col-sm-4"></div>
        </div>
      </div>
    </div>

app/views/products/show.html.erb
<br>
<div class="container">
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
      <div class="panel panel-default">
        <div clasS="panel-heading">
          <h1>Detalles del producto</h1>
        </div>
      <div class="panel-body">
        <p>Nombre: <%= @product.nombre %></p>
        <p>Modelo: <%= @product.modelo %></p>
        <p>Marca: <%= @product.marca %></p>
        <p>Catagoria: <%= @product.categoria %></p>
        <p>Cantidad: <%= @product.cantidad %></p>
        <p>Ubicacion: <%= @product.ubicacion %></p>
        <% if logged_in? %>
          <% if is_admin? %>
            <p>Precio de compra: $<%= @product.p_compra %></p>
          <% end %>
        <% end %>
        <p>Precio de venta: $<%= @product.p_venta %></p>
        <p>Codigo de barra: <%= @product.cod_barra %></p>
        <p>Observaciones: <%= @product.observacion %></p>
      </div>
      <div class="panel-footer">
        <% if logged_in? %>
          <% if is_admin? %>

              <div class= "row">
                <div class= "col-sm-5">
                  <div class="btn-group" role="group" aria-label="...">
                    <%= link_to edit_product_path(@product), { class: "btn btn-sm btn-warning" } do %>
                      <span class="glyphicon glyphicon-pencil"> Editar </span>
                    <% end %>
                    <%= link_to @product, method: :delete, data: { confirm: "¿Estas seguro?" }, class: "btn btn-sm btn-danger"  do %>
                      <span class="glyphicon glyphicon-trash"> Eliminar </span>
                    <% end %>
                  </div>
                </div>
                <div class="col-sm-5"></div>
                <div class="col-sm-2">
                  <%= link_to 'Volver', products_path, { class: "btn btn-md btn-info" } %>
                </div>
              </div>
          <% end %>
        <% else %>
        <div class= "row">
          <div class="col-sm-2">
            <%= link_to 'Volver', products_path, { class: "btn btn-md btn-info" } %>
          </div>
        </div>
        <% end %>

      </div>
    </div>
    <div class="col-md-3"></div>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<ul class="users">
  <%= render @users %>
</ul>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
Hola